// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynbndzwwacdlzdaqwuxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYm5kend3YWNkbHpkYXF3dXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTA3MjIsImV4cCI6MjA2Njk2NjcyMn0.6NGDsJle-Jkjfs0uc-0aP7GdCLBw2UONHHctNQzIHbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});